# Generated by Django 4.0.1 on 2022-01-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('completed', models.SmallIntegerField(choices=[('Done', 1), ('Doing', 2), ('Undone', 3)])),
            ],
        ),
    ]
